### ISSUE TITLE
Route error?

### ISSUE THREAD

**Issue by screamworks** [kunks001/bookable#2]
I installed the bookable gem and was starting a project for a hotel, anyways when I tried a route, "root 'bookings#index''" it did not go through. It kept showing the "welcome abroad" page for some reason...

**Comment by kunks001** [comment]
Hi, I tried replicating your error but couldn't, although if you copied and pasted from your routes file it may simply be because you typed 'bookings#index'' with single quotes on one end and double at the other. In any case, because bookings are nested resources and belong to the thing being booked, you can't root directly to the bookings index. You currently have to access bookings through a resource.

**Comment by screamworks** [comment]
Thanks for the fast reply! Sorry about that I did use correct quotes but while typing about the issue used " on accident. So in this case I would have to generate a controller and a separate view and use the "render" bookings for it to work? Sorry for the questions I'm new to rails and haven't seen much of nested resources. What I'm trying to create is a hotel booking app if that helps.
